-- Adds the Half Marathon Plan and its workouts. Run once in the Supabase SQL editor.
with new_plan as (
  insert into plans (title, cover_url, estimate_weeks)
  values ('Half Marathon Plan', 'assets/photos/half-marathon/half-marathon-plan.webp', 8)
  returning id
)
insert into workouts (plan_id, title, week, date, phase, summary, session, cover_url, week_cover_url, estimate_minutes, discipline)
select id, v.title, v.week, v.date, v.phase, v.summary, v.session, v.cover_url, v.week_cover_url, v.estimate_minutes, v.discipline
from new_plan, (values
  ('Easy Run', 1, '2026-01-06'::date, 'Recovery Phase', 'An easy, conversational-pace run to build aerobic base without adding fatigue.', null, 'assets/photos/half-marathon/easy-run.webp', 'assets/photos/half-marathon/half-marathon-week-1.webp', 20, '{"metric":{"kind":"duration","value":"20 min"},"target":{"label":"Target pace","value":"6:15-6:45 /km"},"mainSet":"Easy, continuous running at a conversational effort, legs only with no structure."}'::jsonb),
  ('Maintenance Swim', 1, '2026-01-08'::date, 'Recovery Phase', 'A steady maintenance swim to keep aerobic fitness ticking over alongside run training.', null, 'assets/photos/half-marathon/quality-run.webp', null, 35, '{"metric":{"kind":"distance","value":"1200 m"},"target":{"label":"Target effort","value":"RPE 5-6 / 10 (main set)"},"warmup":"100 m easy swimming.","mainSet":"5 x 200 m at RPE 5-6/10 steady effort, with 30 seconds rest between reps.","cooldown":"100 m easy swimming."}'::jsonb),
  ('Easy Run', 1, '2026-01-10'::date, 'Recovery Phase', 'A relaxed run focused purely on time on feet rather than pace.', null, 'assets/photos/half-marathon/easy-run.webp', null, 40, '{"metric":{"kind":"distance","value":"6 km"},"target":{"label":"Target pace","value":"6:15-6:45 /km"},"mainSet":"Easy, continuous running at a conversational effort. Focus on time on feet, not pace."}'::jsonb),
  ('Quality Run', 2, '2026-01-13'::date, 'Build Phase', 'A structured interval session to build speed and running economy.', null, 'assets/photos/half-marathon/quality-run.webp', 'assets/photos/half-marathon/half-marathon-week-2.webp', 35, '{"metric":{"kind":"duration","value":"35 min"},"target":{"label":"Target pace","value":"5:00-5:20 /km (reps)"},"warmup":"10 min easy running.","mainSet":"6 x 2 min at RPE 7/10, with 90 sec jog recovery between reps.","cooldown":"5 min easy running."}'::jsonb),
  ('Easy Run', 2, '2026-01-15'::date, 'Build Phase', 'An easy, conversational-pace run to build aerobic base without adding fatigue.', null, 'assets/photos/half-marathon/easy-run.webp', null, 30, '{"metric":{"kind":"duration","value":"30 min"},"target":{"label":"Target pace","value":"6:15-6:45 /km"},"mainSet":"Easy, continuous running at a conversational effort."}'::jsonb),
  ('Long Run', 2, '2026-01-17'::date, 'Build Phase', 'A continuous long run to build aerobic durability with no pace pressure.', null, 'assets/photos/half-marathon/long-run.webp', null, 65, '{"metric":{"kind":"distance","value":"10 km"},"target":{"label":"Target pace","value":"6:15-6:45 /km"},"mainSet":"Continuous easy running to build aerobic durability. No pace target, run by feel at RPE 4-5/10."}'::jsonb),
  ('Quality Run', 3, '2026-01-20'::date, 'Build Phase', 'A structured interval session to build speed and running economy.', null, 'assets/photos/half-marathon/quality-run.webp', 'assets/photos/half-marathon/half-marathon-week-3.webp', 40, '{"metric":{"kind":"duration","value":"40 min"},"target":{"label":"Target pace","value":"5:15-5:35 /km (reps)"},"warmup":"10 min easy running.","mainSet":"5 x 3 min at RPE 7/10, with 2:30 jog recovery between reps.","cooldown":"5 min easy running."}'::jsonb),
  ('Maintenance Swim', 3, '2026-01-22'::date, 'Build Phase', 'A steady maintenance swim to keep aerobic fitness ticking over alongside run training.', null, 'assets/photos/half-marathon/quality-run.webp', null, 35, '{"metric":{"kind":"distance","value":"1200 m"},"target":{"label":"Target effort","value":"RPE 5-6 / 10 (main set)"},"warmup":"100 m easy swimming.","mainSet":"5 x 200 m at RPE 5-6/10 steady effort, with 30 seconds rest between reps.","cooldown":"100 m easy swimming."}'::jsonb),
  ('Long Run', 3, '2026-01-24'::date, 'Build Phase', 'A continuous long run to build aerobic durability with no pace pressure.', null, 'assets/photos/half-marathon/long-run.webp', null, 78, '{"metric":{"kind":"distance","value":"12 km"},"target":{"label":"Target pace","value":"6:15-6:45 /km"},"mainSet":"Continuous easy running to build aerobic durability. No pace target, run by feel at RPE 4-5/10."}'::jsonb),
  ('Quality Run', 4, '2026-01-27'::date, 'Build Phase', 'A structured interval session to build speed and running economy.', null, 'assets/photos/half-marathon/quality-run.webp', 'assets/photos/half-marathon/half-marathon-week-4.webp', 40, '{"metric":{"kind":"duration","value":"40 min"},"target":{"label":"Target pace","value":"5:15-5:35 /km (reps)"},"warmup":"10 min easy running.","mainSet":"4 x 4 min at RPE 7-8/10, with 3 min jog recovery between reps.","cooldown":"5 min easy running."}'::jsonb),
  ('Easy Run', 4, '2026-01-29'::date, 'Build Phase', 'An easy, conversational-pace run to build aerobic base without adding fatigue.', null, 'assets/photos/half-marathon/easy-run.webp', null, 30, '{"metric":{"kind":"duration","value":"30 min"},"target":{"label":"Target pace","value":"6:15-6:45 /km"},"mainSet":"Easy, continuous running at a conversational effort."}'::jsonb),
  ('Long Run', 4, '2026-01-31'::date, 'Build Phase', 'A continuous long run to build aerobic durability with no pace pressure.', null, 'assets/photos/half-marathon/long-run.webp', null, 91, '{"metric":{"kind":"distance","value":"14 km"},"target":{"label":"Target pace","value":"6:15-6:45 /km"},"mainSet":"Continuous easy running to build aerobic durability. No pace target, run by feel at RPE 4-5/10."}'::jsonb),
  ('Easy Run', 5, '2026-02-03'::date, 'Deload Phase', 'A genuinely light, easy-effort run to allow the body to absorb recent training.', null, 'assets/photos/half-marathon/easy-run.webp', 'assets/photos/half-marathon/half-marathon-week-5.webp', 25, '{"metric":{"kind":"duration","value":"25 min"},"target":{"label":"Target pace","value":"6:15-6:45 /km"},"mainSet":"Easy, continuous running at RPE 3/10, genuinely light, this is a deload week."}'::jsonb),
  ('Maintenance Swim', 5, '2026-02-05'::date, 'Deload Phase', 'A steady maintenance swim to keep aerobic fitness ticking over alongside run training.', null, 'assets/photos/half-marathon/quality-run.webp', null, 35, '{"metric":{"kind":"distance","value":"1200 m"},"target":{"label":"Target effort","value":"RPE 5-6 / 10 (main set)"},"warmup":"100 m easy swimming.","mainSet":"5 x 200 m at RPE 5-6/10 steady effort, with 30 seconds rest between reps.","cooldown":"100 m easy swimming."}'::jsonb),
  ('Long Run', 5, '2026-02-07'::date, 'Deload Phase', 'A reduced-volume long run to stay relaxed while recovering from recent training load.', null, 'assets/photos/half-marathon/long-run.webp', null, 58, '{"metric":{"kind":"distance","value":"9 km"},"target":{"label":"Target pace","value":"6:15-6:45 /km"},"mainSet":"Continuous easy running at RPE 3-4/10. Reduced volume this week, keep it relaxed."}'::jsonb),
  ('Quality Run', 6, '2026-02-10'::date, 'Peak Phase', 'A tempo session to sharpen sustained race-pace fitness.', null, 'assets/photos/half-marathon/quality-run.webp', 'assets/photos/half-marathon/half-marathon-week-6.webp', 45, '{"metric":{"kind":"duration","value":"45 min"},"target":{"label":"Target pace","value":"5:35-5:55 /km (reps)"},"warmup":"10 min easy running.","mainSet":"3 x 8 min tempo effort at RPE 7/10, with 3 min jog recovery between reps.","cooldown":"5 min easy running."}'::jsonb),
  ('Easy Run', 6, '2026-02-12'::date, 'Peak Phase', 'An easy, conversational-pace run to build aerobic base without adding fatigue.', null, 'assets/photos/half-marathon/easy-run.webp', null, 30, '{"metric":{"kind":"duration","value":"30 min"},"target":{"label":"Target pace","value":"6:15-6:45 /km"},"mainSet":"Easy, continuous running at a conversational effort."}'::jsonb),
  ('Long Run', 6, '2026-02-14'::date, 'Peak Phase', 'A long run that finishes at goal half marathon effort to rehearse race pace under fatigue.', null, 'assets/photos/half-marathon/long-run.webp', null, 95, '{"metric":{"kind":"distance","value":"15 km"},"target":{"label":"Target pace","value":"6:15-6:45 /km, finishing 5:26-5:56 /km"},"mainSet":"Continuous long run at RPE 4-5/10, building durability. Run the final 15-20 minutes at goal half marathon effort."}'::jsonb),
  ('Quality Run', 7, '2026-02-17'::date, 'Peak Phase', 'A continuous tempo run at goal race effort to build race-specific fitness.', null, 'assets/photos/half-marathon/quality-run.webp', 'assets/photos/half-marathon/half-marathon-week-7.webp', 40, '{"metric":{"kind":"duration","value":"40 min"},"target":{"label":"Target pace","value":"5:26-5:56 /km"},"warmup":"10 min easy running.","mainSet":"20 min continuous tempo running at goal half marathon effort.","cooldown":"10 min easy running."}'::jsonb),
  ('Maintenance Swim', 7, '2026-02-19'::date, 'Peak Phase', 'A steady maintenance swim to keep aerobic fitness ticking over alongside run training.', null, 'assets/photos/half-marathon/quality-run.webp', null, 35, '{"metric":{"kind":"distance","value":"1200 m"},"target":{"label":"Target effort","value":"RPE 5-6 / 10 (main set)"},"warmup":"100 m easy swimming.","mainSet":"5 x 200 m at RPE 5-6/10 steady effort, with 30 seconds rest between reps.","cooldown":"100 m easy swimming."}'::jsonb),
  ('Long Run', 7, '2026-02-21'::date, 'Peak Phase', 'The final big long run, finishing at goal half marathon effort to rehearse race pace under fatigue.', null, 'assets/photos/half-marathon/long-run.webp', null, 107, '{"metric":{"kind":"distance","value":"17 km"},"target":{"label":"Target pace","value":"6:15-6:45 /km, finishing 5:26-5:56 /km"},"mainSet":"Continuous long run at RPE 4-5/10, building durability. Run the final 20-30 minutes at goal half marathon effort."}'::jsonb),
  ('Shakeout Run', 8, '2026-02-24'::date, 'Taper Phase', 'A very light shakeout jog to keep the legs loose ahead of race day.', null, 'assets/photos/half-marathon/easy-run.webp', 'assets/photos/half-marathon/half-marathon-week-8.webp', 20, '{"metric":{"kind":"duration","value":"20 min"},"target":{"label":"Target effort","value":"RPE 2 / 10"},"mainSet":"Very easy jog, legs loose, with no effort or pace focus."}'::jsonb),
  ('Race Day', 8, '2026-02-28'::date, 'Taper Phase', 'Race day, the half marathon itself, run at goal pace.', null, 'assets/photos/half-marathon/quality-run.webp', null, 120, '{"metric":{"kind":"distance","value":"21.1 km"},"target":{"label":"Target pace","value":"5:26-5:56 /km"},"mainSet":"Race day. Run the full half marathon at goal pace."}'::jsonb)
) as v(title, week, date, phase, summary, session, cover_url, week_cover_url, estimate_minutes, discipline);

